version: '3'
services:
  postgres:
    image: postgres:14                # 稳定版本，兼容 NocoBase[4,12](@ref)
    container_name: nocobase_db
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_PASSWORD: nocobase
      POSTGRES_DB: nocobase
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # 数据持久化[9,11](@ref)
    ports:
      - "5432:5432"                   # 暴露端口给宿主机
    restart: always
